### ISSUE TITLE
单选 / 多选框不正常显示

### ISSUE THREAD

**Issue by imgradeone** [vinceliuice/Fluent-gtk-theme#1]
**系统** Manjaro 20.2.1 GNOME

**可复现软件** GNOME Tweaks

![屏幕截图(4046)](https://user-images.githubusercontent.com/30969327/107519620-74714900-6beb-11eb-925e-514579d7e8cc.png)
↑ Fluent 主题（单选按钮不显示）

![屏幕截图(4047)](https://user-images.githubusercontent.com/30969327/107519812-a7b3d800-6beb-11eb-8ac4-2d18fbbc36da.png)
↑ Matcha 主题（正常）

**Comment by vinceliuice** [comment]
下载最新的重新安装一遍试试，应该又是图标文件读取权限出问题了

**Comment by imgradeone** [comment]
尝试在 `~/.themes` 文件夹下安装，没有问题
