### ISSUE TITLE
Blank space in context menu Nautilus 3.38 (Debian Bullseye)

### ISSUE THREAD

**Issue by JVintimilla** [vinceliuice/Fluent-gtk-theme#103]
![Captura de pantalla de 2022-05-02 11-38-29](https://user-images.githubusercontent.com/90857245/166286089-7771a5f3-6d80-45c1-bf67-eabaa6c72e7e.png)

I'm not quite sure if this a Debian/Nautilus 3.38 related bug, but you can see that at the bottom of the context menu there is a blank space that displays absolutely nothing.
I thought you should know about this, because I've also encountered this same issue using Colloid theme.

**Comment by vinceliuice** [comment]
not a theme issue, app issue
