### ISSUE TITLE
Inconsistent GTK and KDE title bars

### ISSUE THREAD

**Issue by Shaddwo** [vinceliuice/Fluent-gtk-theme#11]
All your other themes that I have used are consistent between Gtk and KDE but this one is not

![image](https://user-images.githubusercontent.com/72974062/118385127-fc6f5080-b629-11eb-9226-c1d0ec40e7e0.png)

Could you fix this? I personally prefer the KDE titlebar style

**Comment by vinceliuice** [comment]
You mean the bakground color?

**Comment by Shaddwo** [comment]
No, like the title bar buttons

**Comment by vinceliuice** [comment]
Gtk theme titlebuttons style follow the icon theme, if you are using fluent icon theme, then it will be the same

**Comment by Shaddwo** [comment]
Oh ok. Thanks
