### ISSUE TITLE
Theme does not seem to apply to nautilus

### ISSUE THREAD

**Issue by dragonattheend** [vinceliuice/Fluent-gtk-theme#110]
![image](https://user-images.githubusercontent.com/83570780/175187885-5f43354d-905b-4b1d-8088-3f723ada77fb.png)

On your screenshots and in some apps (for example settings) there is a blue vertical line next to a selected folder/tab
Also window decorations and top bar overall looks different in nautilus

**Comment by dragonattheend** [comment]
It got resolved , somehow ..
I think it's related to blur my shell extension, but not exactly sure how

**Comment by aditiapratama** [comment]
confirm on my side too
![image](https://user-images.githubusercontent.com/982553/176317092-ab1f9438-69ef-4461-bbae-fd7146794bd3.png)

**Comment by vinceliuice** [comment]
Install the last version on github, I renamed Fluent-dark to Fluent-Dark to fix this issue

**Comment by dragonattheend** [comment]
> Install the last version on github, I renamed Fluent-dark to Fluent-Dark to fix this issue

thank you! the buttons are fixed now, but the panel in nautilus is different for some reason. It works in settings panel though ...

![image](https://user-images.githubusercontent.com/83570780/176582260-4bfdf169-1692-4eff-bbb2-ac5d84118a24.png)

**Comment by dragonattheend** [comment]
![image](https://user-images.githubusercontent.com/83570780/176584071-a288f7c1-9000-4d7f-8c38-db8986f62317.png)


![image](https://user-images.githubusercontent.com/83570780/176584107-98573f6e-fa62-41e8-9cd9-9676c61977c4.png)


also selection or hovering is red in some apps (settings, terminal) and none in others (nautilus, image viewer)

**Comment by dragonattheend** [comment]
The trick is not to use the dark style in appearance. So weird.

**Comment by vinceliuice** [comment]
Use the Fluent-Dark, not Fluent-dark, last gnome 42 can not use dark themes

**Comment by anyone00** [comment]
Maybe include flag in install.sh to rename dark variant to something else?

**Comment by dragonattheend** [comment]
> Use the Fluent-Dark, not Fluent-dark, last gnome 42 can not use 'dark' name themes

It still doesn't work with the dark style in fedora appearance settings 

Fluent-Dark works when the style is set to light in Appearance , when it's set to dark, the windows look like adwaita
