### ISSUE TITLE
Broken radio button

### ISSUE THREAD

**Issue by Mofiqul** [vinceliuice/Fluent-gtk-theme#12]
Hi thanks for the wonderful theme, but I am having these unusual radio button in thunar and Firefox. 
This issue is only in dark variant of theme
*Thunar*
![1](https://user-images.githubusercontent.com/23612580/120368814-27e38200-c330-11eb-8c03-7f1b9d9522f9.png)
*Firefox*
![2](https://user-images.githubusercontent.com/23612580/120368832-2b770900-c330-11eb-82fa-51e459e35cc5.png)

**Comment by vinceliuice** [comment]
Did you installed the last version from github？

**Comment by Mofiqul** [comment]
Installing  directly from GitHub fixed the issue. Thanks
