### ISSUE TITLE
Not Working in Gnome 42.4

### ISSUE THREAD

**Issue by mumer012001** [vinceliuice/Fluent-gtk-theme#127]
Please make it available for Gnome 42.4.

**Comment by hl2guide** [comment]
yes please, I've got the wallpaper and icons working but not the theme for the shell:

![1](https://user-images.githubusercontent.com/17044982/191226655-e4126778-d038-41f5-b939-640452718b12.png)

I ran: `dnf install gtk-murrine-engine` beforehand.

**Comment by mumer012001** [comment]
Oh sorry, I wasn't supposed to post this here, it was for the Blur Me extension.
