### ISSUE TITLE
Fluent theme breaks on gnome shell 43 action center

### ISSUE THREAD

**Issue by Htet-Wai-Yan** [vinceliuice/Fluent-gtk-theme#130]
I was using fluent theme on my Fedora 36 with gnome 42 and set the shell theme to fluent. Then, I updated to fedora 37 beta with gnome 43 and fluent theme is not properly working on shell. Please see the screen shot below.

![fluent-gnome-shell](https://user-images.githubusercontent.com/35678784/193509923-bb10755c-6a5a-4370-9f20-acee8e4c8d55.png)

![dropdown](https://user-images.githubusercontent.com/35678784/193510028-bf699560-d2b2-497b-841a-7cea11dfe8fc.png)

**Comment by dayfuaim** [comment]
I have the similar problem in Ubuntu 22.10 beta, GNOME 43, Dark mode:
![image](https://user-images.githubusercontent.com/1274699/193510918-ac1dc680-a0e2-4276-a7bf-26fc3af30771.png)

The rest of theme works just perfectly.

Please, fix it. :)

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by dayfuaim** [comment]
@Htet-Wai-Yan
I do this manually via `git pull` (I have already git-cloned the repo) & `install.sh` with params I need.

**Comment by Htet-Wai-Yan** [comment]
@dayfuaim I did as you said. plus, I deleted all the fluent theme folders inside the user/share/themes and reinstalled it. Now, it is working. Thank you so much.
