### ISSUE TITLE
Issues with Gnome Calender 43 titlebar

### ISSUE THREAD

**Issue by astro-ray** [vinceliuice/Fluent-gtk-theme#132]
the size of title bar in gnome is problematic in the new gnome calender 43
![image](https://user-images.githubusercontent.com/69363775/195982925-05f0c3e9-cd4a-44fc-8543-4c06faae92d9.png)

**Comment by g1bber1sh** [comment]
same here, its actually whats keeping me from using gnome at the moment

**Comment by ritamsaha00** [comment]
@g1bber1sh if you update to gnome 43, the issue with calendar should should go away
