### ISSUE TITLE
Support for flatpak applications

### ISSUE THREAD

**Issue by oneproxima** [vinceliuice/Fluent-gtk-theme#135]
It seems like the theme doesn't apply to flatpak applications. Is there a way to get this to work or a misunderstanding by me?

**Comment by vinceliuice** [comment]
use this: https://github.com/refi64/stylepak

**Comment by oneproxima** [comment]
thank you, I misunderstood that's would solve this problem.

**Comment by oneproxima** [comment]
thank you, I misunderstood that's would solve this problem.
