### ISSUE TITLE
Upgrade to gnome 43

### ISSUE THREAD

**Issue by RogerioTDS** [vinceliuice/Fluent-gtk-theme#137]
Hello. Could you update it to gnome 43? Because the correction for libadwaita, in gnome 43, is not possible.
![Captura de tela de 2022-12-15 00-51-25](https://user-images.githubusercontent.com/120617835/207768913-c76b5431-a478-4641-b461-6e4deb6484f5.png)

**Comment by vinceliuice** [comment]
Download last version: https://github.com/vinceliuice/Fluent-gtk-theme/releases/tag/2022-12-15
