### ISSUE TITLE
Please add support for Newsflash app

### ISSUE THREAD

**Issue by vihu** [vinceliuice/Fluent-gtk-theme#142]
Hello, thanks for making an awesome theme!

I tried it on my xfce4 desktop and noticed that the [Newsflash](https://flathub.org/apps/details/com.gitlab.newsflash) is not correctly supported. For example:

![image](https://user-images.githubusercontent.com/3199183/222505122-bbe5c952-53b4-479e-9d38-b02664ecfd0c.png)

That typically shows up as a check mark symbol for read/unread items. Can you please add support for this app. Thanks!

**Comment by vinceliuice** [comment]
isn't this a icon theme issue ?

**Comment by vihu** [comment]
> isn't this a icon theme issue ?

Ah fair enough, I am using <https://github.com/vinceliuice/Fluent-icon-theme> specifically Fluent Dark. I can close this and open the issue on that repository.
