### ISSUE TITLE
BUG: No square tweak with gtk4/libadwaita applications

### ISSUE THREAD

**Issue by matleborgne** [vinceliuice/Fluent-gtk-theme#149]
![no_square](https://user-images.githubusercontent.com/101802281/235153628-1b6ac1c9-7419-47b0-988f-118df4b34fa2.gif)

Hello,
When installing with `--tweaks square`, the square only applies with old gtk3 apps.

**Comment by vinceliuice** [comment]
run: ./install.sh --tweaks square -l

**Comment by matleborgne** [comment]
Sadly it does not work, my exact command line is 
`bash install.sh -t grey -c light -s compact -i arch -l --tweaks solid square`

I tried with the `-l` in the end (we never know), but same result.
For libadwaita apps, still no square (in NixOS, I tried on Arch, Fedora, Ubuntu too).

The rest (color, compact, etc.) is okay.

**Comment by vinceliuice** [comment]
Fixed now
