### ISSUE TITLE
Feature: Let user use custom top-panel icon

### ISSUE THREAD

**Issue by matleborgne** [vinceliuice/Fluent-gtk-theme#150]
Hello,

It would be great to let user change the top-panel icon, defined in current installation by `--icon <distro>`.
The best would be to let user change path of the icon, or explain in the README how to find and replace the actual icon.

As a NixOS user, I'm stuck with Windows/Mac/Ubuntu or Arch icon.
For now, a workaround is to use dash-to-panel + arc-menu and use a custom icon in arc-menu, but it's not lightweight at all.

**Comment by vinceliuice** [comment]
Added support for nixos now

**Comment by matleborgne** [comment]
Thank's, your themes and icon packs are awesome, bravo :)
I close the issue then.
