### ISSUE TITLE
Zorin Theme Support

### ISSUE THREAD

**Issue by Mas4hmad** [vinceliuice/Fluent-gtk-theme#151]
Hi, i just want to report the issue affects Zorin OS Core (GNOME Desktop).
the power window shows weird button in bottom right (reboot/shutdown/logoff).
focused/selected/expanded menu in system menu shows weird gradient button while it should show flat button.

Showcase video:
[Screencast from 09-06-23 13:17:26.webm](https://github.com/vinceliuice/Fluent-gtk-theme/assets/45534607/06a04283-46cc-4715-a212-14bed2759bd2)

**Comment by vinceliuice** [comment]
What about now ?

**Comment by Mas4hmad** [comment]
now, it is fixed by commit 6862de9. the menu and window should show with no weird gradient.
this issue will be closed.

thanks for response.

Showcase video:
[Screencast from 09-06-23 20:43:50.webm](https://github.com/vinceliuice/Fluent-gtk-theme/assets/45534607/d24754b4-b4d6-4d5d-96c9-37e64d006fca)
