### ISSUE TITLE
Some xfce issues

### ISSUE THREAD

**Issue by Dejweed** [vinceliuice/Fluent-gtk-theme#154]
Hello! Here are some things I've noticed:
- The compact version doesn't include the xfwm theme
- Tweaks are not applied to xfwm theme
- Xfwm theme could have a border just like gtk

Xfce appearance settings:
- With light theme, the background and text have the same color when hovered
- When holding a button and releasing it somewhere else, the border gets bigger, reaching the window edge

https://github.com/vinceliuice/Fluent-gtk-theme/assets/65261588/6cf5e0b2-ba8f-4e12-ac11-0e7aec7640d7

**Comment by Dejweed** [comment]
@vinceliuice please take another look, using square tweaks with xfwm results in circle buttons

**Comment by vinceliuice** [comment]
Fixed now
