### ISSUE TITLE
Undo tweaks

### ISSUE THREAD

**Issue by C-O-D** [vinceliuice/Fluent-gtk-theme#161]
Hi, at first thanks for your impressing themes!
Just two questions:
   How can I undo tweaks like 'square' or e.g. 'noborder'?
   How can I apply 'square' to other colors like e.g. red?

Thanks

**Comment by vinceliuice** [comment]
1, just reinstall it without those option
2, `./install.sh -t red --tweaks square`

**Comment by C-O-D** [comment]
Ah ok, thanks a lot...
