### ISSUE TITLE
New release? 

### ISSUE THREAD

**Issue by TafkaMax** [vinceliuice/Fluent-gtk-theme#166]
Could we get a new release? NixOS uses the release version and the latest fixes for gnome 45 are helpful.

https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/data/themes/fluent-gtk-theme/default.nix#L26

**Comment by TafkaMax** [comment]
Ping.

**Comment by xuanruiqi** [comment]
Yeah, a new release is necessary

**Comment by TafkaMax** [comment]
Thanks!
