### ISSUE TITLE
Gnome 46

### ISSUE THREAD

**Issue by simonesestito** [vinceliuice/Fluent-gtk-theme#170]
Hi, I've just updated to Gnome 46 (Wayland, Arch Linux) and I can see that some UI elements are broken:

- Notifications are totally broken (the most important thing): 
![image](https://github.com/vinceliuice/Fluent-gtk-theme/assets/24279760/b1c9ae26-e1e6-4a52-a322-917c111dbcf9)
- The dock has some strange dark background color: 
![image](https://github.com/vinceliuice/Fluent-gtk-theme/assets/24279760/f411e2c3-a5f1-4acf-9eea-b0b9362e5c02)
- Same thing for the calendar:
![image](https://github.com/vinceliuice/Fluent-gtk-theme/assets/24279760/524c0b59-0410-4c3c-81d6-7d9bcd0856e4)
- The volume indicators are a little too big: 
![image](https://github.com/vinceliuice/Fluent-gtk-theme/assets/24279760/ecbecb9f-1382-4c82-a7a7-3f4c59f9c146)
- Search bar is too light: 
![image](https://github.com/vinceliuice/Fluent-gtk-theme/assets/24279760/b20843c8-34e3-4848-a1fb-77e10651dec5)

# Steps I have tried
```sh
rm -rf ~/.themes
mkdir ~/.themes
git clone https://github.com/vinceliuice/Fluent-gtk-theme
cd Fluent-gtk-theme
./install.sh -c dark -i simple -l --tweaks round
```

Then, re-apply the theme and reboot the system.

I have also tried with just:
```sh
./install.sh -c dark
```
but same bugs occur

**Comment by matleborgne** [comment]
Exact same bugs here (ArchLinux + Wayland + GNOME).

To complete the bug report, I would add that if I disable "user theme" extension (which has Fluent-gtk-theme as setting), all of these graphic bugs disappear.

So the issue does effectively come from the theme.

**Comment by Smoerrebroed** [comment]
Same bug here - Arch + Wayland + GNOME, but it also shows on Xorg. Switched to Adwaita shell theme ==> gone

**Comment by matleborgne** [comment]
Problems seem to be solved by the last commit.
Thanks :)
