### ISSUE TITLE
Notifications are not visible in notifications list - Gnome 46

### ISSUE THREAD

**Issue by marvinhrivera** [vinceliuice/Fluent-gtk-theme#173]
Hello,

I just wanted to report that the notification list is empty on gnome shell 46 as follows:

![image](https://github.com/vinceliuice/Fluent-gtk-theme/assets/112781564/0e7cd931-e087-423a-97a8-6801e5b84211)

I know there are notifications because if I press the Clear button it will show "No Notifications" and going by back to Adwaita theme it will display the missing notifications:

![image](https://github.com/vinceliuice/Fluent-gtk-theme/assets/112781564/32231c28-2323-41d5-96f7-9e908675ea6d)

**Comment by marvinhrivera** [comment]
Hello, sorry to bother but after the last commit applied the notifications list is still missing, I tried removing the theme completely and cloning again but the issue remains on both dark and light modes.

**Comment by vinceliuice** [comment]
What about now ?

**Comment by marvinhrivera** [comment]
Awesome!! Indeed, it is working now, thank you!!
