### ISSUE TITLE
Minor CSS issue with ArcMenu 

### ISSUE THREAD

**Issue by scottyphillips** [vinceliuice/Fluent-gtk-theme#176]
Good evening,

I am absolutely loving this theme. I have noticed another minor issue when using it with Arc Menu on GNOME 46.1. There is a little bit of overdraw with Shadow highlighting on the menu items where the shadow box goes past the main box and it also has a curved edge when the menu itself is square. Hopefully the pictures show what I mean more clearly. 

This is fluent-compact-light on ArcMenu 11 style.

![Screenshot from 2024-05-17 19-05-00](https://github.com/vinceliuice/Fluent-gtk-theme/assets/26150540/e292b8a6-c031-44d1-aef7-5ac1df449feb)

This is fluent-compact-dark on ArcMenu 11 style.
![Screenshot from 2024-05-17 19-05-38](https://github.com/vinceliuice/Fluent-gtk-theme/assets/26150540/cc94b189-752f-4ca6-9048-de778f510464)

Another couple of examples on different Arc Menus:

![Screenshot from 2024-05-17 19-07-24](https://github.com/vinceliuice/Fluent-gtk-theme/assets/26150540/f234d1a7-2a6f-415c-9073-a0d6dd966cf1)

![Screenshot from 2024-05-17 19-07-52](https://github.com/vinceliuice/Fluent-gtk-theme/assets/26150540/d8148781-3cc1-459a-ae90-41e7762fe0f7)

Once again, thanks so much for a great theme.

**Comment by scottyphillips** [comment]
Thank you, please accept my sincere gratitude for all your hard work.

**Comment by vinceliuice** [comment]
Thank you!
