### ISSUE TITLE
Missing theme on some cinnamon windows

### ISSUE THREAD

**Issue by SakiiCode** [vinceliuice/Fluent-gtk-theme#195]
The Software Sources settings and the progress dialog during updates are showing as unthemed
Tested Linux Mint 21.3, 22.1, latest release and master

![Képernyőkép – 2024-12-20 17-30-49](https://github.com/user-attachments/assets/858d6155-649d-4d58-95b7-457985fba010)

**Comment by vinceliuice** [comment]
You need Install this theme with sudo

**Comment by SakiiCode** [comment]
This was the solution, thank you!
