### ISSUE TITLE
Blur effect

### ISSUE THREAD

**Issue by narisuzu** [vinceliuice/Fluent-gtk-theme#28]
Is it possible to add some blur effect to the transparent part (like dock, top-bar ...)? 
That will make the theme more suitable with the icon theme.

**Comment by vinceliuice** [comment]
https://extensions.gnome.org/extension/4236/blur-me/

**Comment by vinceliuice** [comment]
https://extensions.gnome.org/extension/3193/blur-my-shell/

**Comment by vinceliuice** [comment]
Run `./install.sh --tweaks blur` 

![screenshot-blur](https://raw.githubusercontent.com/vinceliuice/Fluent-gtk-theme/master/screenshot-blur.jpg?raw=true)

**Comment by narisuzu** [comment]
Thanks for your effort

**Comment by vinceliuice** [comment]
You are welcome!
