### ISSUE TITLE
problem about window decoration

### ISSUE THREAD

**Issue by narisuzu** [vinceliuice/Fluent-gtk-theme#29]
when I use `Fluent-lignt` with rounded corner option. the title bar of the GTK applications are dark style, and not rounded
![image](https://user-images.githubusercontent.com/16162768/128591931-86a0fa6b-1ba0-427b-bb6a-3c337382a4a5.png)

**Comment by narisuzu** [comment]
this occurs occasionally. it's strange

**Comment by vinceliuice** [comment]
What's this app?

**Comment by narisuzu** [comment]
any gtk apps will behave like that.
the app in the pic is transmission(GTK)

**Comment by vinceliuice** [comment]
What's your desktop?

**Comment by narisuzu** [comment]
Gnome 40.3.0

**Comment by vinceliuice** [comment]
![Screenshot-20210807200937-1166x1106](https://user-images.githubusercontent.com/7604295/128599676-3632bdb5-a7f3-4e8e-b0a7-6b95ced33ffb.png)

**Comment by vinceliuice** [comment]
![Screenshot-20210807201029-2306x1952](https://user-images.githubusercontent.com/7604295/128599694-b92e5e1b-2bb4-49f0-8afd-029e6cdddb56.png)

**Comment by vinceliuice** [comment]
I don't know why you get this issue, it's all ok on my desktop
