### ISSUE TITLE
wallpaper crashed in gnome 40

### ISSUE THREAD

**Issue by narisuzu** [vinceliuice/Fluent-gtk-theme#30]
I set up the wallpaper in the `src/wallpaper` folder properly, but the wallpaper became black at 18:00. 
other dynamic wallpapers don't have this problem.
![image](https://user-images.githubusercontent.com/16162768/128597002-58a025ab-b9d3-4e2b-9d37-0b13ac2cf257.png)
**Use official dynamic wallpaper of gnome**
![image](https://user-images.githubusercontent.com/16162768/128597040-bd5ed621-c70d-4ead-ab9d-1e3b0bf7369e.png)

**Comment by vinceliuice** [comment]
I'll fix this!

**Comment by vinceliuice** [comment]
Fixed!
