### ISSUE TITLE
suggestion for focused list items' decoration 

### ISSUE THREAD

**Issue by narisuzu** [vinceliuice/Fluent-gtk-theme#32]
![Fluent Design](https://docs.microsoft.com/en-us/windows/apps/design/signature-experiences/images/geometry_hero_1880.png)
According to this pic from Microsoft. the round radius of the small blue rounded corner rectangle in the left of the focused item seems to be bigger than this theme does currently. 

in the pic, the rounded corner on the top and bottom sides of that rectangle looks like semi-circles.

![image](https://user-images.githubusercontent.com/16162768/128659086-6a0f495e-3088-4660-b33c-54ff9c1afe97.png)

on my device, the same rectangle's corner looks sharper.

**Comment by vinceliuice** [comment]
No problem! I'll update this
