### ISSUE TITLE
Unify the shadow depth of different apps' windows

### ISSUE THREAD

**Issue by narisuzu** [vinceliuice/Fluent-gtk-theme#33]
Hi. 

**Terminal**
![image](https://user-images.githubusercontent.com/16162768/128682981-b0182278-8465-4dc6-b958-3b94f17095b1.png)

**Visual Studio Code**
![image](https://user-images.githubusercontent.com/16162768/128683081-0e6e9eb6-f8b9-41fc-b956-c5e75bc9a408.png)

the both screenshots were captured when their windows were focused and with same white background.
and obviously, the first one has a lighter shadow border. their titlebar colours are a little bit different as well.
Could you plz fix this issue?

**Comment by vinceliuice** [comment]
Visual Studio Code use non-CSD windows on gnome, this shadow is drawn by gnome's windows manager and is not controled by the theme, so I can do nothing about this!

**Comment by narisuzu** [comment]
what a pity. anyway thanks for your reply!
