### ISSUE TITLE
Possible to have a Teal/Matcha colored Variant?

### ISSUE THREAD

**Issue by Big-FG** [vinceliuice/Fluent-gtk-theme#34]
I noticed that in the _color_pallete there is some values for a Teal variant, would it be at all possible to have a variant of Fluent in this color/color similar to Matcha? 

I realize that doing these themes is time consuming and not simple (Ive tried doing it previously myself) but that is the only thing for me missing from this theme  for at least me. You're one of the most active theme devs and your stuff is consistently up to date along with this theme being a nice in between of materia & adwaita when rounded corners are enabled which is perfect.

If not no worries and feel free to close this issue as its not exactly an "issue"

**Comment by vinceliuice** [comment]
No problem! i can add this

**Comment by vinceliuice** [comment]
Added
