### ISSUE TITLE
Wallpapers install script problem

### ISSUE THREAD

**Issue by fblais** [vinceliuice/Fluent-gtk-theme#35]
Hi.
The install script must be run with root rights.
However, the backgrounds pictures folder is then created with root rights as well.
Therefore in gnome-control-center, the pictures are not available.
With root privileges I had to change the folders (fluent, fluent-building and fluent-mountain) properties to user rights to get the wallpapers available.
Maybe at the end of the script, you should add some code to change these folders properties.

Thanks!

**Comment by vinceliuice** [comment]
The pictures are not available? why, it works all right on my desktop
![Screenshot from 2021-08-16 08-25-50](https://user-images.githubusercontent.com/7604295/129497369-bc1a8aab-7add-4cbf-89c6-17386c3756f8.png)

**Comment by fblais** [comment]
Did you check the ownership of the fluent, fluent-building and fluent-mountain) folders?
When I ran the install script, they were owned by root, and that was the reason I couldn't see them.
Changing the ownership and folder/file access properties was the key to getting the wallpapers working correctly.
I can only describe what I'm experiencing, believe it or not, and I'm not really a newbie with Linux.
I'm running Debian 11 by the way.

**Comment by vinceliuice** [comment]
But it installed in `/usr/share/backgrounds/`  it should owned by root right?

**Comment by vinceliuice** [comment]
![Screenshot from 2021-08-16 09-07-02](https://user-images.githubusercontent.com/7604295/129498780-3f01d7b4-b754-42e0-b5d0-0c7f269e942a.png)
All files in that dir `/usr/share/backgrounds/` owned by root, it should works

**Comment by vinceliuice** [comment]
I'll download a debian 11 for testing if it's issue about the system

**Comment by vinceliuice** [comment]
![VirtualBox_Debian_16_08_2021_10_16_52](https://user-images.githubusercontent.com/7604295/129502751-c30bac17-38bf-434f-834c-e4a532d9c21f.png)

**Comment by vinceliuice** [comment]
It works all well on Debian 11

**Comment by vinceliuice** [comment]
This install shell is for system timed wallpapers, if you want use normal wallpapers just download the [wallpapers](https://github.com/vinceliuice/Fluent-gtk-theme/tree/Wallpaper) and select one set it to wallpaper (on `wallpaper-1080p` `wallpaper-2k` `wallpaper-4k`)
