### ISSUE TITLE
Audio output selection panel looks out of place (see screenshots) [GNOME40]

### ISSUE THREAD

**Issue by EncryptedCicada** [vinceliuice/Fluent-gtk-theme#37]
<h1> Info </h1>

- **OS:** Arch Linux
- **Kernel:** Linux 5.13.12-arch1-1
- **Gnome shell version:** 40.4 stock
- **Using:** `fluent-gtk-theme-git` package from AUR built with custom args.
- **Args used:** `-t all -i arch -c light -c dark --tweaks solid -d "$pkgdir/usr/share/themes"`
- **Extras:** Using `fluent-cursor-theme-git` and `fluent-icon-theme-git` in conjunction with the theme.

<h1> Possible issue </h1>

The sound output selector panel appeares after the system detects a device being connected to the 3.5mm jack but the appearance of the panel seems to be out of place with respect to the overall solid theme. When the background is textual or has a lot of black and white elements, the visibility of the panel seems to be an issue without the contrast to make it out. 

<h1> Screenshots </h1>

![Screenshot from 2021-08-20 19-54-11](https://user-images.githubusercontent.com/52757733/130255219-10097fd8-a498-4022-b141-0cba5833cc0d.png)

![Screenshot from 2021-08-20 20-08-29](https://user-images.githubusercontent.com/52757733/130255236-fe793ea7-b6b5-48a0-a5a4-7bb2e4315b44.png)

<h1> Expected Behaviour </h1>

The flag `--tweaks solid` should have ensured the installation of only the solid/non-translucent theme variant.

<h1> Not tried yet: </h1>

Manually installing the latest release and trying to reproduce the issue. (I'm willing to do that if it's needed to resolve the issue)

**Comment by vinceliuice** [comment]
Is this `Audio output selection` a gnome-shell extension?

**Comment by vinceliuice** [comment]
Never mind, it's fixed now
