### ISSUE TITLE
not display icon

### ISSUE THREAD

**Issue by Saliizan** [vinceliuice/Fluent-gtk-theme#39]
When I set the theme to compact mode, the icon above is not displayed. Where is the problem?

![1](https://user-images.githubusercontent.com/58263865/131027391-fa2329dc-8ec2-4e56-a657-05e7c09bacae.png)

**Comment by stenioas** [comment]
@Saliizan, rename file "activities.svg" to "activities-small.svg" into the folder "gnome-shell/assets" and the icon will appear.

**Comment by vinceliuice** [comment]
I'll fix this
