### ISSUE TITLE
Titlebar shows plus on maximize instead of square

### ISSUE THREAD

**Issue by onkoe** [vinceliuice/Fluent-gtk-theme#40]
This may be an intended feature, but I've noticed that on GNOME, the maximize button on the window titlebar is a plus instead of a square as it is on other desktop environments. I prefer the square. Is there any way I can change the plus to be a square? I have attached a screenshot below so you can see the difference. 
![2021-08-28_19-31](https://user-images.githubusercontent.com/66580279/131234317-3a477378-7008-4c15-9c2c-59acdf8aa62a.png)

**Comment by vinceliuice** [comment]
You need change your icon theme, this icon is in the icon theme

**Comment by onkoe** [comment]
Thanks, that fixed it!
