### ISSUE TITLE
Chinese Input Candidate Box - Content Misaligned

### ISSUE THREAD

**Issue by HymanZHAN** [vinceliuice/Fluent-gtk-theme#5]
Thank you for the beautiful themes! Have been using your Tela and Qogir themes for over 2 years now. This Fluent theme is another solid one and I am enjoying it so far!

I just want to report a slight glitch I noticed:

![image](https://user-images.githubusercontent.com/26806995/109406156-cc76b200-7944-11eb-8c02-e800f5957cdd.png)

In the candidate box of the default Chinese IME, the candidates are not aligned at the center but to the top. Could you take a look at it? Thank you very much!

**Comment by vinceliuice** [comment]
修复了！

**Comment by HymanZHAN** [comment]
@vinceliuice 非常感谢！

**Comment by vinceliuice** [comment]
😆️ 不客气
