### ISSUE TITLE
How to clone wallpapers repo?

### ISSUE THREAD

**Issue by fanr10** [vinceliuice/Fluent-gtk-theme#50]
Great job!
How to clone wallpapers repo?

In the clone code button, the cloned repository is the theme's repository.

**Comment by vinceliuice** [comment]
git clone -b  Wallpaper https://github.com/vinceliuice/Fluent-gtk-theme.git

**Comment by fanr10** [comment]
Thank you!

**Comment by fanr10** [comment]
Regards
