### ISSUE TITLE
Notification event time is out of design

### ISSUE THREAD

**Issue by dayfuaim** [vinceliuice/Fluent-gtk-theme#54]
Theme is awesome and I use it as default in Ubuntu 21.10 (GNOME 40), but notification's event time is out of design:
![Снимок экрана от 2021-10-19 20-23-48](https://user-images.githubusercontent.com/1274699/137960825-cce2bcef-2f01-40d4-b89f-2d551179b5a8.png)

I guess it should be smaller (~0.75em), slightly higher and not such bright.
And (probably) right adjusted. ;)

**Comment by Hezkore** [comment]
A lot of shell stuff's out of style for me.
I use the `noborder` tweak, so no application has any border or anything, but every shell popup like the notification area or start menu, all have a border.
Looks very out of place.

![Screenshot from 2021-11-04 19-47-59](https://user-images.githubusercontent.com/1727541/140401339-fda95b18-0984-4fd8-98ad-19eb353cccf9.png)

**Comment by vinceliuice** [comment]
I'll fix this!

**Comment by vinceliuice** [comment]
Fixed now

**Comment by dayfuaim** [comment]
@vinceliuice OK, border is fixed. It's very good. :)
And what about message event time?
