### ISSUE TITLE
Some input fields cuts off text

### ISSUE THREAD

**Issue by Hezkore** [vinceliuice/Fluent-gtk-theme#59]
Some input fields gets their text cut off, especially if running the 'compact' theme variant.

Here's the settings dialog for the Gnome extensions 'Tray Icons: Reloaded' using the non-compact theme:
![2021-11-01_18-06](https://user-images.githubusercontent.com/1727541/139711173-d2c54c8b-2cb0-4f20-a0ab-a595c7d462d9.png)

Here's using the compact theme:
![2021-11-01_18-09](https://user-images.githubusercontent.com/1727541/139711459-5ab8ebaa-ac34-4888-9900-116247fed71a.png)

**Comment by vinceliuice** [comment]
Fixed!
