### ISSUE TITLE
Windows 11 Fluent UI

### ISSUE THREAD

**Issue by ErickHoward** [vinceliuice/Fluent-gtk-theme#62]
Could you update the theme to have the style of the new Windows 11 fluent controls please?

**Comment by vinceliuice** [comment]
The round version is Windows 11 fluent controls

**Comment by ErickHoward** [comment]
Some things don't seem to be exactly the same, the text boxes have the old style

**Comment by ErickHoward** [comment]
![image](https://user-images.githubusercontent.com/78889625/140596249-1e7d3bea-da19-4a65-b5b2-03a7a01a68f5.png)
this is what it looks like in WinUI 2.6

**Comment by vinceliuice** [comment]
I'll update it in the future, it's developing not released
