### ISSUE TITLE
Round + solid = transparent background in the Gnome Shell menus for the Dark variant

### ISSUE THREAD

**Issue by lfom** [vinceliuice/Fluent-gtk-theme#63]
Thank you for this theme, probably its Compact version is the sleekest GTK+ theme so far!

When using `--tweaks round solid noborder` the dark variant results in a transparent background for the menus in Gnome shell.

![Screenshot from 2021-11-11 18-24-35](https://user-images.githubusercontent.com/15659999/141371300-15200f2a-28a4-4b8c-9bd0-46fdfee9f74a.png)

Also, some minor issues that may need some tweaking:

1. When using `--tweaks solid` the topbar has the same color as the active app topbar/headerbar when using the dark variant, what looks very weird when a window "touches" the topbar (please see first screenshot below)
2. The window border seems to be invisible when there is no other window behind it, only the desktop (please see the second attached screenshot = non solid version).

![Screenshot from 2021-11-11 18-23-05](https://user-images.githubusercontent.com/15659999/141371369-c494bce2-1a13-4a55-8e5e-bf466b37ea11.png)

![Screenshot from 2021-11-11 17-40-00](https://user-images.githubusercontent.com/15659999/141370125-89408802-d8f3-41ea-9dc6-9e65ff8d2b1b.png)

Screenshots taken on a VM running Debian Unstable/Gnome 41.1

Regards

**Comment by lfom** [comment]
Same problems on Garuda/Arch (Gnome 41.1).

**Comment by vinceliuice** [comment]
Fixed already

**Comment by vinceliuice** [comment]
You just need to restart your desktop

**Comment by lfom** [comment]
@vinceliuice 
It seems to be working fine now on 41.1, thanks. But now it has the transparent background in Gnome Shell 3.38.5 and dialogs like logout and restart look really weird, even after restarting the DE. I also notice that Firefox (using the default stock theme) now does not have round borders anymore...

![Screenshot from 2021-11-22 02-26-39](https://user-images.githubusercontent.com/15659999/142805752-d0813308-d7b9-4a39-a41c-573fbc5c2508.png)

**Comment by vinceliuice** [comment]
Fixed now

**Comment by lfom** [comment]
Regarding Firefox, it seems that the sharp corners happen in Wayland for all themes besides the default system one, so it is not related to Fluent.
Once again, thank you a lot for your themes!
Regards
