### ISSUE TITLE
Gnome Photos huge bar

### ISSUE THREAD

**Issue by jawadalkassim** [vinceliuice/Fluent-gtk-theme#64]
![Screenshot from 2021-11-12 23-03-43](https://user-images.githubusercontent.com/48631694/141534354-15a505a1-db1d-41f7-82e3-3365ed52c02b.png)

**Comment by vinceliuice** [comment]
App issue, not a theme issue

**Comment by jawadalkassim** [comment]
> App issue, not a theme issue

Ah ok didn't know that
