### ISSUE TITLE
dashed lines when scrolled

### ISSUE THREAD

**Issue by icewyvrn** [vinceliuice/Fluent-gtk-theme#68]
Hello, dashed lines appears at the top when I scroll, it happens in all applications. GNOME 41.1

![image](https://user-images.githubusercontent.com/41411360/142523930-e2462e0c-737e-4865-8c51-2a0114de64a1.png)

**Comment by vinceliuice** [comment]
Yes, yiu can change to the default theme adwaita, it also have this, this is not a issue

**Comment by icewyvrn** [comment]
it does not have the dashed lines on default theme
![image](https://user-images.githubusercontent.com/41411360/142531130-109e85b8-e15d-4b47-889c-305b11235127.png)

**Comment by vinceliuice** [comment]
I'll check this

**Comment by vinceliuice** [comment]
Removed!
