### ISSUE TITLE
i've made a mistake

### ISSUE THREAD

**Issue by denikris** [vinceliuice/Fluent-gtk-theme#69]
hi vince,

can you edit the line **108** which is `border-left:2px solid #0078D4;` to `border-left:2px solid $primary;` in the **_xfce.scss** files, it was my pull request, and can you add fix for [xfce4-docklike-plugin](https://gitlab.xfce.org/panel-plugins/xfce4-docklike-plugin)

```
//change these colors according to your color palette
#docklike-plugin button{min-width:32px;min-height:36px;}
#docklike-plugin button.hover_group{background-color:rgba(255,255,255,0.1);}
#docklike-plugin button.active_group{background-color:rgba(255,255,255,0.12);}
#docklike-plugin button.active_group.hover_group{background-color:rgba(46, 179, 152,0.12);}
```
![image](https://user-images.githubusercontent.com/16707606/143011181-f22e606e-eae0-43ef-b436-6c6c7fc2e31b.png)
![image](https://user-images.githubusercontent.com/16707606/143011500-c8d262b8-0b2d-4f7b-8d77-e1cd56f3aae0.png)

thank you

**Comment by vinceliuice** [comment]
No problem!
