### ISSUE TITLE
Nemo URL bar focus color

### ISSUE THREAD

**Issue by SmileYzn** [vinceliuice/Fluent-gtk-theme#74]
Hi, i did not know if is possible or it is a bug. 
But url bar in nemo file manager differ from other input border color when hover:

https://i.imgur.com/bLUb9ji.png

Ps. Nice work with updates and theme

**Comment by vinceliuice** [comment]
I'll update this, I take this color from edge browser

**Comment by SmileYzn** [comment]
Thanks
