### ISSUE TITLE
Fedora icon seems to be of the wrong color

### ISSUE THREAD

**Issue by HymanZHAN** [vinceliuice/Fluent-gtk-theme#77]
Again, thanks for creating such a nice theme!

I notice the color of the Fedora icon is not very legible in dark, which is also different from the screenshots in the README.

![Screenshot from 2021-11-26 14-29-56](https://user-images.githubusercontent.com/26806995/143624248-c7d295ba-b6f4-4ab0-b9a7-0f83ebf565aa.png)

As shown in the screenshot, I installed it with `./install.sh -i fedora` command. The selected shell theme is the default Fluent theme:

![Screenshot from 2021-11-26 14-42-21](https://user-images.githubusercontent.com/26806995/143624533-61bff262-f96e-458f-88a0-36276c5e5e2a.png)

Update: I am using Fedora 35 with Gnome 41.1.

**Comment by vinceliuice** [comment]
Download the last update and try again, fixed now!

**Comment by HymanZHAN** [comment]
Thanks for the quick follow-up! The color looks correct now.
