### ISSUE TITLE
Workspace thumbnails not showing in Fluent shell theme (Gnome 40)

### ISSUE THREAD

**Issue by OnePinkSheep** [vinceliuice/Fluent-gtk-theme#8]
Workspace thumbnails seem to be missing when using the Fluent shell theme in Gnome 40.

This is what it looks like using the Fluent shell theme: https://i.imgur.com/EJfqkit.png

As you can see, the thumbnails that's supposed to show right below the search bar is blank.

This is what it looks like using the default shell theme (I think it's Adwaita): https://i.imgur.com/TiTbxve.png

**Comment by vinceliuice** [comment]
Gnome-shell 40 theme not finished

**Comment by vinceliuice** [comment]
Fixed
