### ISSUE TITLE
Lack of contrast in nautilus

### ISSUE THREAD

**Issue by ABarnob** [vinceliuice/Fluent-gtk-theme#82]
![image](https://user-images.githubusercontent.com/34279631/148670605-3883ca17-e5b2-4d6c-b32c-6e7f83a9f3ad.png)
 
Well, here we go again. I really love your work. I've been trying out some of your themes lately.
I've noticed the same issue in Fluent that I mentioned earlier in Colloid ([Issue #15](https://github.com/vinceliuice/Colloid-gtk-theme/issues/15)).

**Comment by vinceliuice** [comment]
No problem, I'll fix this
