### ISSUE TITLE
Installation is not system wide(not for all packages) even if I use sudo

### ISSUE THREAD

**Issue by MineEaster** [vinceliuice/Fluent-gtk-theme#84]
So I am using latest non LTS Minimal version of Manjaro Gnome and after a normal installation of this theme everything look as it is supposed to look but after some time I notices that some default application have weird looks. I searched google and found I have to install theme at qt or whatever....I cant understand properly. So I need help to solve this issue.
![Screenshot from 2022-01-12 18-47-43](https://user-images.githubusercontent.com/76616749/149147745-b92ef6fa-9e8f-4a1c-bf95-53d52f85a88e.png)

**Comment by vinceliuice** [comment]
It's a qt app, not gtk app

**Comment by MineEaster** [comment]
> It's a qt app, not gtk app

ye ik but is there a way install this theme in kvanmtum
