### ISSUE TITLE
Button size is too thin

### ISSUE THREAD

**Issue by vicky-nike** [vinceliuice/Fluent-gtk-theme#85]
I installed it through source.

![Screenshot from 2022-01-15 23-39-37](https://user-images.githubusercontent.com/40816229/149632986-bfa49e9e-4645-4a86-9fd8-d1a6b860fb87.png)

**Comment by vicky-nike** [comment]
The issue got solved, looks like unite extension was somehow messing with the themes.

After disabling the extension and then rebooting the system solved the issue.

**Comment by vinceliuice** [comment]
What's your gnome-shell version?

**Comment by vicky-nike** [comment]
gnome 41.2

After resetting my gdm-theme, and restarting the system the issue got solved.

**Comment by vinceliuice** [comment]
I use a svg file for button's style now
