### ISSUE TITLE
Windows not rounded.

### ISSUE THREAD

**Issue by AspirinEny** [vinceliuice/Fluent-gtk-theme#86]
Windows not rounded. 窗口圆角不可用。
![2022-01-16 11-46-52 的屏幕截图](https://user-images.githubusercontent.com/20171531/149646504-08fedd53-b636-4bcc-853b-6830c89633a1.png)
![2022-01-16 11-47-05 的屏幕截图](https://user-images.githubusercontent.com/20171531/149646507-0eac258d-616c-4783-9d76-48f4c2acd569.png)
![2022-01-16 11-47-33 的屏幕截图](https://user-images.githubusercontent.com/20171531/149646509-892cbee4-7420-48cb-b1d4-7aeab36ab455.png)

**Comment by AspirinEny** [comment]
The first image shows what the window corners actually look like, but the situation in the window's screenshots (image 2, 3) is normal, it's weird..
第一张图片即实际看到的窗口圆角，但是窗口截图输出却很正常，是不是少设置了什么东西？

**Comment by vinceliuice** [comment]
关闭blur me这个插件

**Comment by AspirinEny** [comment]
关了之后使用 --tweaks blur 选项的时候，透明度太高了，可以在什么地方设置吗？
![2022-01-16 12-58-03 的屏幕截图](https://user-images.githubusercontent.com/20171531/149647908-808ff91f-1e8f-4935-b6ca-04ecff3583e9.png)

**Comment by vinceliuice** [comment]
试一下这个吧: https://aur.archlinux.org/packages/mutter-rounded/

**Comment by vinceliuice** [comment]
或者安装普通版本的主题不要blur版本

**Comment by AspirinEny** [comment]
我放弃使用 blur 参数了，它和 round 参数、mutter-rounded 软件包均不兼容。

**Comment by vinceliuice** [comment]
建议直角的那个主题可以使用blur参数，圆角的blur me支持不行
