### ISSUE TITLE
Blur not working

### ISSUE THREAD

**Issue by cfpwastaken** [vinceliuice/Fluent-gtk-theme#97]
The Blur version doesnt seem to be working.
My installation command:
```shell
./install.sh --tweaks round --tweaks blur
```
Output of that:
```shell
Install rounded windows version ...
Install blur version ...
Installing '/home/cfp/.themes/Fluent-round'...
Install rounded windows version ...
Install blur version ...
Installing '/home/cfp/.themes/Fluent-round-compact'...
Install rounded windows version ...
Install blur version ...
Installing '/home/cfp/.themes/Fluent-round-light'...
Install rounded windows version ...
Install blur version ...
Installing '/home/cfp/.themes/Fluent-round-light-compact'...
Install rounded windows version ...
Install blur version ...
Installing '/home/cfp/.themes/Fluent-round-dark'...
Install rounded windows version ...
Install blur version ...
Installing '/home/cfp/.themes/Fluent-round-dark-compact'...

Done.
```
Blur Me is installed. I enabled the theme using the User Themes extension.
Result:
![image](https://user-images.githubusercontent.com/44261356/158071200-3325576a-01d1-4041-adef-f59be5577035.png)

**Comment by vinceliuice** [comment]
Did you changed the ght theme? why it's still yaru themes?

**Comment by cfpwastaken** [comment]
OOOH NOW I FIGURED IT OUT!

**Comment by cfpwastaken** [comment]
for everyone here in the future, you have to change this one too.
![image](https://user-images.githubusercontent.com/44261356/158180686-69161b05-e79f-4d96-a7e6-beb1ef29d6e7.png)
